Description: This template is for the VPC deployment and will include all resources related to the VPC including subnets and internet gateways spread across availability zones.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
         - Key: stack
           Value: production
  
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: stack
          Value: production
  
  VPCGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC
      Tags:
        - Key: stack
          Value: production
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: stack
          Value: production

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: !Ref VPC
      CidrBlock: 10.0.20.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: stack
          Value: production
  
  NATGateway1:
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
      - Key: stack
        Value: production

  NATGatewayEIP1:
   Type: AWS::EC2::EIP
   Properties:
      Domain: vpc
      Tags:
      - Key: stack
        Value: production

  PublicRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: stack
          Value: production

  PublicRoute1:
    Type: AWS::EC2::Route
    DependsOn: IGW
    Properties:
        RouteTableId: !Ref PublicRouteTable1
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref IGW
        Tags:
        - Key: stack
          Value: production

  PublicSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: !Ref PublicSubnet1
      RouteTableId:
        Ref: !Ref PublicRouteTable1

